courier/config/routes.rb
Courier::Application.routes.draw do

  scope "(:locale)", :locale => /es|en-US|en/ do
    resources :direccions

    resources :paquetes

    resources :compania

    resources :facturas

    resources :tipo_pagos

    resources :historicos

    resources :ordens

    resources :personas

    resources :empleados

    resources :enviar

    resources :despachar

    resources :recolectar

    resources :admin

    resources :service

  end

  get "courier/index"

  match '/:locale/contenido', :to => 'courier#contenido', :as => "cont"

  match '/:locale/seguimiento/', :to => 'courier#seguimiento', :as => "seg"

  match '/:locale/empleado/', :to => 'admin#empleados', :as => "emple"

  match '/:locale/admin/', :to => 'admin#index', :as => "adm"

  match 'paquetes/new/:id', :to => 'paquetes#new', :via => 'get', :as => "newpa"

  match '/:locale/despachar', :to => 'despachar#index', :as => "despachador"

  match ':locale/ruta/:id', :to => 'despachar#ver', :as => "ver"

  match ':locale/recolectores/', :to => 'despachar#recolectores', :as => "recolec"

  match ':locale/simulacion/', :to => 'despachar#simulacion', :as => "simul"

  match ':locale/guardarOrden/:id', :to => 'despachar#guardarOrden' , :as => "guardarOrden"

  match ':locale/recoleccionExterna', :to => 'despachar#recoleccionExterna' , :as => "recoExter"

  match ':locale/consultaExterna/:id', :to => 'despachar#consultaExterna' , :as => "consulExter"

  match ':locale/notificar', :to => 'ordens#notificar' , :as => "noti"
  
   match ':locale/nuevanotificacion/:id', :to => 'ordens#nuevanotificacion' , :as => "notis"

  match ':locale/recolectar/', :to => 'recolectar#index', :as => "reco"

  match ':locale/orden/:id', :to => 'recolectar#orden', :as => "recorden"

  match 'tracking/:id', :to => 'enviar#gen_xml', :via => 'get', :as => "genxml"

match ':locale/prueba/', :to => 'service#prueba', :as => "prueba"
  match 'getorden/:id', :to => 'service#getorden', :as => "getorden", :via => 'get'
  match 'setorden', :to => 'service#setorden', :as => "setorden", :via => 'post'

  root :to => "courier#index"

  get 'contenido' => 'courier#contenido'

  match ':controller(/:action(/:id(.:format)))'

end

courier/app/views/layouts/application.html.erb
<html>
	<head>
		<title>Courier</title>
		<%= stylesheet_link_tag :all %>
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
	</head>
	<body>

		<div id="wrapper">
			<div id="header">
				<div id="logo">
					<h1>
					<a href="<%= cont_path %>">Courier UCAB </a>
					</h1>
				</div>
			</div>
			<!-- end #header -->
			<div id="menu">
				<ul>
					<li class="current_page_item">
						<a href="<%= cont_path %>">Principal</a>
					</li>
				</ul>
			</div>
			<!-- end #menu -->
			<div id="page">
				<%= yield %>
			</div>
			<!-- end #page -->
		</div>
		<div id="footer">
		</div>
		<!-- end #footer -->
	</body>
</html>

courier/app/views/layouts/enSistema.html.erb
<html>
	<head>
		<title>Courier</title>
		<%= stylesheet_link_tag :all %>
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
	</head>
	<body>

		<div id="wrapper">
			<div id="header">
				<div id="logo">
					<h1>
					<a href="<%= cont_path %>">Courier UCAB</a>
					</h1>
				</div>
				<div id="idioma">
					<h3>	<%= link_to 'es', idioma('es') %> |
					<%= link_to 'en', idioma('en') %></h3>
				</div>
			</div>
			<!-- end #header -->
			<div id="menu">
				<ul>
					<li class="current_page_item">
						<a href="<%= cont_path %>"><%= t('principal.principal') %></a>
					</li>
				</ul>
				<ul>
					<li id='salir'>
						<%= link_to t('principal.salir'),  root_url, :action=> :destruir %>
					</li>
				</ul>
			</div>
			<!-- end #menu -->
			<div id="page">
				<div id="page-bgtop">
					<div id="page-bgbtm">
						<div id="content">

							<%= yield %>

							<div style="clear: both;">
								&nbsp;
							</div>
						</div>
						<!-- end #content -->
						<div id="sidebar">
							<ul>
								<li>
									<h2><%= t('principal.datos') %></h2>
									<ul id='datos'>
										<li>
											<%= t('principal.nombre') %>:
											<% if !(session[:email].nil?) %>
											<%= "" + session[:nombre] + " " + session[:apellido] %>
											<%end%>
										</li>
										<li>
											Email: <% if !(session[:email].nil?) %>
											<%= "" + session[:email] %>
											<%end%>
										</li>
									</ul>
								</li>
								<% if session[:rol].nil? %>
								<li>
									<h2><%= t('principal.categoria') %></h2>
									<ul>
										<li>
											<%= link_to  t('principal.dir'), direccions_path %>
										</li>
										<li>
											<%= link_to t('principal.tdc'), tipo_pagos_path %>
										</li>
										<li>
											<%= link_to t('principal.orden'), ordens_path %>
										</li>
										<li>
											<%= link_to t('principal.factura'), facturas_path %>
										</li>
										<li>
											<%= link_to 'Notificacion', noti_path %>
										</li>
									</ul>
								</li>
								<% else %>
								<% if session[:rol] == 1 %>
								<li>
									<h2><%= t('principal.admin') %></h2>
									<ul>
										<li>
											<%= link_to t('principal.clientes'), adm_path %>
										</li>
										<li>
											<%= link_to t('principal.empleados'), emple_path %>
										</li>
									</ul>
								</li>
								<%end%>
								<% if session[:rol] == 3 or session[:rol] == 1 %>
								<li>
									<h2><%= t('principal.despachar') %></h2>
									<ul>
										<li>
											<%= link_to t('principal.asignarr'), despachador_path %>
										</li>
										<li>
											<%= link_to t('principal.recolector'), recolec_path %>
										</li>
										<li>
											<%= link_to t('principal.simulacion'), simul_path %>
										</li>
										<li>
											<%= link_to 'Recoleccion externa', recoExter_path %>
										</li>
									</ul>
								</li>
								<%end%>
								<% if session[:rol] == 2 or session[:rol] == 1%>
								<li>
									<h2><%= t('principal.recolectar') %></h2>
									<ul>
										<li>
											<%= link_to t('principal.rutasasig'), recolectar_path(session[:id]) %>
										</li>
										<li>
											<%= link_to t('principal.notificarre'), reco_path %>
										</li>
									</ul>
								</li>
								<%end%>
								<%end%>
							</ul>
						</div>
						<div style="clear: both;">
							&nbsp;
						</div>
					</div>
				</div>
			</div>
			<!-- end #page -->
		</div>
		<div id="footer">
		</div>
		<!-- end #footer -->
	</body>
</html>