courier/config/routes.rb
Courier::Application.routes.draw do

  scope "(:locale)", :locale => /es|en-US|en/ do
    resources :direccions

    resources :paquetes

    resources :compania

    resources :facturas

    resources :tipo_pagos

    resources :historicos

    resources :ordens

    resources :personas

    resources :empleados

    resources :enviar

    resources :despachar

    resources :recolectar

    resources :admin

    resources :service

  end

  get "courier/index"

  match '/:locale/contenido', :to => 'courier#contenido', :as => "cont"

  match '/:locale/seguimiento/', :to => 'courier#seguimiento', :as => "seg"

  match '/:locale/empleado/', :to => 'admin#empleados', :as => "emple"

  match '/:locale/admin/', :to => 'admin#index', :as => "adm"

  match 'paquetes/new/:id', :to => 'paquetes#new', :via => 'get', :as => "newpa"

  match '/:locale/despachar', :to => 'despachar#index', :as => "despachador"

  match ':locale/ruta/:id', :to => 'despachar#ver', :as => "ver"

  match ':locale/recolectores/', :to => 'despachar#recolectores', :as => "recolec"

  match ':locale/simulacion/', :to => 'despachar#simulacion', :as => "simul"

  match ':locale/guardarOrden/:id', :to => 'despachar#guardarOrden' , :as => "guardarOrden"

  match ':locale/recoleccionExterna', :to => 'despachar#recoleccionExterna' , :as => "recoExter"

  match ':locale/consultaExterna/:id', :to => 'despachar#consultaExterna' , :as => "consulExter"

  match ':locale/notificar', :to => 'ordens#notificar' , :as => "noti"
  
   match ':locale/nuevanotificacion/:id', :to => 'ordens#nuevanotificacion' , :as => "notis"

  match ':locale/recolectar/', :to => 'recolectar#index', :as => "reco"

  match ':locale/orden/:id', :to => 'recolectar#orden', :as => "recorden"

  match 'tracking/:id', :to => 'enviar#gen_xml', :via => 'get', :as => "genxml"

match ':locale/prueba/', :to => 'service#prueba', :as => "prueba"
  match 'getorden/:id', :to => 'service#getorden', :as => "getorden", :via => 'get'
  match 'setorden', :to => 'service#setorden', :as => "setorden", :via => 'post'

  root :to => "courier#index"

  get 'contenido' => 'courier#contenido'

  match ':controller(/:action(/:id(.:format)))'

end

courier/app/models/paquete.rb
class Paquete < ActiveRecord::Base

  # Validaoms los formularios de la pagina Paquete, y relacionamos la tabla.
  validates :nombre         , :presence => true
  validates :peso         , :presence => true
  validates_numericality_of :peso
  validates :descripcion , :presence => true
  belongs_to :ordens
  belongs_to :personas
  validate :validate
  
  # Metodo el cual valida que el peso del paquete no sea menor o igual a cero,
  # enviando un error de este llegar a ser negativo.
  def validate()
    errors.add(:peso, "debe ser positivo") if peso < 0
  end
end

courier/app/controllers/paquetes_controller.rb
class PaquetesController < ApplicationController

  # Llamamos al layout enSistema que se encuentra en la carpeta layouts.
  layout "enSistema"
  # Metodo utilizado cuando se accede a la pagina index.
  # GET /paquetes
  # GET /paquetes.xml
  def index

    if (Direccion.where(:personas_id => session[:id]).first && TipoPago.where(:personas_id => session[:id]).first)
      @id=session[:id]
      @paquetes = Paquete.where(:personas_id => @id,:ordens_id => nil)
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @paquetes }
      end
    else
    # Mostramos un error, de no existir una tarjeta de credito y una direcion.
      flash[:error] = t('validartarjeta')
      redirect_to cont_path
    end

  end

  # llamada a motrar una paquete, pasandole un parametro.
  # GET /paquetes/1
  # GET /paquetes/1.xml
  def show
    @paquete = Paquete.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @paquete }
    end
  end

  # llamada a la pagina new de paquete, pasandole un parametro
  # GET /paquetes/new
  # GET /paquetes/new.xml
  def new

    @paquete = Paquete.new
    @orden = params[:id]
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @paquete }
    end
  end

  # Llamamos a la pagina editar de paquete.
  # GET /paquetes/1/edit
  def edit
    @paquete = Paquete.find(params[:id])
  end

  # llamada a crear una paquete, pasandole un parametro.
  # POST /paquetes
  # POST /paquetes.xml
  def create
    @paquete = Paquete.new(params[:paquete])
    respond_to do |format|
      @paquete.personas_id=session[:id]
      if @paquete.save
        NUESTRO_LOG.info "Se guardo el paquete correctamente"
        format.html { redirect_to(paquetes_path, :notice => t('paquetecrear')) }
        format.xml  { render :xml => @paquete, :status => :created, :location => @paquete }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @paquete.errors, :status => :unprocessable_entity }
      end
    end
  end

  # Llamamos al metodo para acualizar la paquete pasandole un parametro.
  # PUT /paquetes/1
  # PUT /paquetes/1.xml
  def update
    @paquete = Paquete.find(params[:id])

    respond_to do |format|
      if @paquete.update_attributes(params[:paquete])
        format.html { redirect_to(@paquete, :notice => t('paqueteactualizar')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @paquete.errors, :status => :unprocessable_entity }
      end
    end
  end

  # Llamada al metodo destruir un paquete, pasandole un parametro.
  # DELETE /paquetes/1
  # DELETE /paquetes/1.xml
  def destroy
    @paquete = Paquete.find(params[:id])
    @paquete.destroy

    respond_to do |format|
      format.html { redirect_to(@paquete) }
      format.xml  { head :ok }
    end
  end
end

courier/app/helpers/paquetes_helper.rb
module PaquetesHelper
  # Helper de vista para validar el boton generarorden
  def validar (id)
    
    @paquete = Paquete.where(:ordens_id => nil, :personas_id => id).first
    if @paquete.nil?
      @paquete =  ""
    else
      @paquete = link_to t('generarorden'), enviar_path(id)
    end
  end
  
end

courier/app/views/paquetes/_form.html.erb
<%= form_for(@paquete) do |f| %>
<% if @paquete.errors.any? %>
<!-- <div id="error_explanation">
<h2><%= pluralize(@paquete.errors.count, "error") %> prohibited this paquete from being saved:</h2>

<ul>
<% @paquete.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div> -->
<% end %>

<%= f.hidden_field :ordens_id, :value => @orden  %>
<div class="field">
	<%= f.label t('nombrez') %>
	<br />
	<%= f.text_field :nombre %>
</div>
<div class="field">
	<%= f.label t('peso') %>
	<br />
	<%= f.text_field :peso %>
</div>
<div class="field">
	<%= f.label t('descripcion') %>
	<br />
	<%= f.text_field :descripcion %>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

courier/app/views/paquetes/edit.html.erb
<h1><%= t('editarpaquete') %></h1>

<%= render 'form' %>

<%= link_to t('mostrar'), @paquete %> |
<%= link_to t('regresar'), ordens_path %>

courier/app/views/paquetes/index.html.erb
<h1><%= t('listadopaquetes')%></h1>

<table>
  <tr>
    <th><%= t('nombrez') %></th>
    <th><%= t('peso') %></th>
    <th><%= t('descripcion') %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @paquetes.each do |paquete| %>
  <tr>
    <td><%= paquete.nombre %></td>
    <td><%= paquete.peso %></td>
    <td><%= paquete.descripcion %></td>
    <td><%= link_to t('mostrar'), paquete %></td>
    <td><%= link_to t('editar'), edit_paquete_path(paquete) %></td>
    <td><%= link_to t('eliminar'), paquete, :confirm => t('eliminarseguro'), :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('nuevopaquete'), new_paquete_path %>
|
<%= validar (@id) %>

courier/app/views/paquetes/new.html.erb
<h1><%= t('nuevopaquete') %></h1>

<%= render 'form' %>

<%= link_to t('regresar'), ordens_path %>

courier/app/views/paquetes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t('nombrez') %>:</b>
  <%= @paquete.nombre %>
</p>

<p>
  <b><%= t('peso') %>:</b>
  <%= @paquete.peso %>
</p>

<p>
  <b><%= t('descripcion') %>:</b>
  <%= @paquete.descripcion %>
</p>


<%= link_to t('editar'), edit_paquete_path(@paquete) %> |
<%= link_to t('regresar'), paquetes_path %>