courier/config/routes.rb
Courier::Application.routes.draw do

  scope "(:locale)", :locale => /es|en-US|en/ do
    resources :direccions

    resources :paquetes

    resources :compania

    resources :facturas

    resources :tipo_pagos

    resources :historicos

    resources :ordens

    resources :personas

    resources :empleados

    resources :enviar

    resources :despachar

    resources :recolectar

    resources :admin

    resources :service

  end

  get "courier/index"

  match '/:locale/contenido', :to => 'courier#contenido', :as => "cont"

  match '/:locale/seguimiento/', :to => 'courier#seguimiento', :as => "seg"

  match '/:locale/empleado/', :to => 'admin#empleados', :as => "emple"

  match '/:locale/admin/', :to => 'admin#index', :as => "adm"

  match 'paquetes/new/:id', :to => 'paquetes#new', :via => 'get', :as => "newpa"

  match '/:locale/despachar', :to => 'despachar#index', :as => "despachador"

  match ':locale/ruta/:id', :to => 'despachar#ver', :as => "ver"

  match ':locale/recolectores/', :to => 'despachar#recolectores', :as => "recolec"

  match ':locale/simulacion/', :to => 'despachar#simulacion', :as => "simul"

  match ':locale/guardarOrden/:id', :to => 'despachar#guardarOrden' , :as => "guardarOrden"

  match ':locale/recoleccionExterna', :to => 'despachar#recoleccionExterna' , :as => "recoExter"

  match ':locale/consultaExterna/:id', :to => 'despachar#consultaExterna' , :as => "consulExter"

  match ':locale/notificar', :to => 'ordens#notificar' , :as => "noti"
  
   match ':locale/nuevanotificacion/:id', :to => 'ordens#nuevanotificacion' , :as => "notis"

  match ':locale/recolectar/', :to => 'recolectar#index', :as => "reco"

  match ':locale/orden/:id', :to => 'recolectar#orden', :as => "recorden"

  match 'tracking/:id', :to => 'enviar#gen_xml', :via => 'get', :as => "genxml"

match ':locale/prueba/', :to => 'service#prueba', :as => "prueba"
  match 'getorden/:id', :to => 'service#getorden', :as => "getorden", :via => 'get'
  match 'setorden', :to => 'service#setorden', :as => "setorden", :via => 'post'

  root :to => "courier#index"

  get 'contenido' => 'courier#contenido'

  match ':controller(/:action(/:id(.:format)))'

end

courier/app/models/orden.rb
class Orden < ActiveRecord::Base

  # Validamos los formularios de la pagina Orden, y relacionamos la tabla.
  validates :nombre	 , :presence => true
  validates :apellido, :presence => true
  validates :estado	 , :presence => true
  belongs_to :personas
  has_one :facturas
  has_many :historicos
  has_many :paquetes
  belongs_to :personas
  # Muestra las rutas de la de la orden buscandolas por un id en la tabla historico
  def self.rutas(id)
    return Historico.find_by_sql('Select h.fecha, h.tipo , d.*, h.id as idHistorico from historicos h, direccions d where h.direccions_id=d.id and h.fecha is not null and h.ordens_id=' + id.to_s + ' order by h.fecha DESC')
  end

  # Metodo que valida la ruta de recoleccion, se busca la ruta pasandole una orden
  # y se le cambia el estado a la orden a recolectada una vez que se haya ejecutado el metodo
  # e inmediatamente se guarda en el historico.
  def self.rutaRecolectada(orden)
    if orden.estado != "Recolectada"
      orden.estado = "Recolectada"
      orden.empleado_id = nil
      @historico = Historico.where(:ordens_id => orden.id, :tipo => "Recolectada").first
      @historico.fecha = Time.now
      orden.save
      @historico.save
      return "La orden se ha recolectado con exito"
    else
      return "La orden ya fue recolectada en otro momento"
    end
  end

  # metodo valida todos los campos cliente, mediante el id del mismo pasado por parametros
  # de estar en la base de datos, revisa que el campo no este vacio.
  def self.validarCliente(cliente)
    if cliente[:email].nil?
      return nil
    else
      @cliente = Persona.where(:email => cliente[:email]).first
      if @cliente.nil?
        return nil
      else
      return @cliente.id
      end
    end
  end

  # metodo valida todos los campos direccion que ninguno que se este pasando por
  # el xml este vacio.
  def self.validarDireccion(direccion)
    if direccion[:nombre].nil? or direccion[:avCalle].nil? or direccion[:resCasa].nil? or direccion[:aptoNumero].nil? or direccion[:urban].nil? or direccion[:ciudad].nil? or direccion[:pais].nil? or direccion[:cPostal].nil? or direccion[:lat].nil? or direccion[:lng].nil?
    return false
    else
    return true
    end
  end

  # metodo valida todos los campos orden, recibidos en el xml, para que estos no sean vacios
  # dependiendo de los mismo retorna un booleano.
  def self.validarOrdenRemota(orden)
    if  orden[:nombre].nil? or orden[:apellido].nil? or orden[:fecha].nil?
    return false
    else
    return true
    end
  end

  # metodo valida todos los campos paquete, recibidos en el xml, para que estos no sean vacios
  # dependiendo de los mismo retorna un booleano.
  def self.validarPaquete(paquete)
    if paquete[:peso].nil? or paquete[:nombre].nil? or paquete[:descripcion].nil?  or paquete[:peso].to_i<=0
    return false
    else
    return true
    end
  end

  # metodo valida todos los campos tarjeta, recibidos en el xml, para que estos no sean vacios
  # dependiendo de los mismo retorna un booleano.
  def self.validartarjeta(tarjeta)
    if tarjeta[:nTDC].nil?
      return nil
    else
      @cliente = TipoPago.where(:nTDC => tarjeta[:nTDC]).first
      if @cliente.nil?
        return nil
      else
      return @cliente.id
      end
    end
  end
  
  # metodo valida todos los campos de la recoleccion, recibidos en el xml, para que estos no sean vacios
  # dependiendo de los mismo retorna un booleano. tambien busca que estos no sean vacios en la base de datos.
  def self.validarrecoleccion(direccion)
    if direccion[:nombre].nil?
      return nil
    else
      @cliente = Direccion.where(:nombre => direccion[:nombre]).first
      if @cliente.nil?
        return nil
      else
      return @cliente.id
      end
    end
  end

  # metodo valida todos los campos de la orden remota, recibidos en el xml, para que estos no sean vacios
  # dependiendo de los mismo retorna un booleano.
  def self.validarRemota(xml)
    @cli = validarCliente(xml[:cliente])
    @tar = validartarjeta(xml[:tarjeta])
    @dir = validarrecoleccion(xml[:direccionrecoleccion])
    if !(@cli.nil?) and validarOrdenRemota(xml[:orden]) and validarPaquete(xml[:paquete]) and validarDireccion(xml[:direccionentrega]) and !(@dir.nil?) and !(@tar.nil?)
      return [@cli,@tar,@dir]
    else
      return nil
    end
  end

  # Metodo valida que las direcciones pasandole un id, y el nombre univoco, para la data traida del xml.
  def self.direcciones(id, nombre)
    return Direccion.find_by_sql("select * from historicos h, direccions d where d.id=h.direccions_id and h.tipo='" + nombre + "' and h.ordens_id=" + id.to_s).first
  end
  
  # metodo que busca las ordenes que se encuentran pendientes por notificar. Que tengan cargo extra de otra compania
  def self.notificaciones
    return Factura.find_by_sql('select o.*, f.costoTotal from ordens o , facturas f where f.ordens_id=o.id and o.notificacion = "alerta"')
  end

end

courier/app/controllers/ordens_controller.rb
class OrdensController < ApplicationController

  # Llamamos al layout enSistema que se encuentra en la carpeta layouts.
  layout "enSistema"
  # GET /ordens
  # GET /ordens.xml
  # Metodo llamado al iniciar la pagina index, y muestra la pagina unicamente si existe session.
  def index
    @ordens = Orden.where(:personas_id => session[:id]).order("created_at DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ordens }
    end
  end

  # llamada a motrar una orden, pasandole un parametro, y buscando un paquete que use este parametro.
  # GET /ordens/1
  # GET /ordens/1.xml
  def show
    @orden = Orden.find(params[:id])
    @paquetes = Paquete.where(:ordens_id => params[:id] )

    # Realizamos dos llamadas a buscar en base de datos para poder crear las facturas del usuario.
    @historico = Orden.rutas(@orden.id)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @orden }
    end
  end

  # llamada a la pagina new de orden, pasandole un parametro y preguntando un parametro de la session del usuario.
  # GET /ordens/new
  # GET /ordens/new.xml
  def new
    if (Direccion.where(:personas_id => session[:id]).first && TipoPago.where(:personas_id => session[:id]).first)
      @orden = Orden.new
      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @orden }
      end
    else
    # Mostramos un error, de no existir una tarjeta de credito y una direcion.
      flash[:error] = t('validartarjeta2')
      redirect_to cont_path
    end
  end

  # Llamamos a la pagina editar de orden.
  # GET /ordens/1/edit
  def edit
    @orden = Orden.find(params[:id])
  end

  # llamada a crear una orden, pasandole un parametro, y preguntando por la sesion del usuario, la fecha actual,
  # fijamos un estado de la orden.
  # POST /ordens
  # POST /ordens.xml
  def create
    @orden = Orden.new(params[:orden])
    @orden.personas_id=session[:id]
    @orden.fecha= Time.now
    @orden.estado = 'Pendiente por Recolectar'
    respond_to do |format|
      if @orden.save
        NUESTRO_LOG.info "Se guardo la orden correctamente"
        format.html { redirect_to(@orden, :notice => 'Orden was successfully created.') }
        format.xml  { render :xml => @orden, :status => :created, :location => @orden }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @orden.errors, :status => :unprocessable_entity }
      end
    end
  end

  # Llamamos al metodo para acualiar la orden pasandole un parametro.
  # PUT /ordens/1
  # PUT /ordens/1.xml
  def update
    @orden = Orden.find(params[:id])

    respond_to do |format|
      if @orden.update_attributes(params[:orden])
        format.html { redirect_to(@orden, :notice => 'Orden was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @orden.errors, :status => :unprocessable_entity }
      end
    end
  end

  # Llamada al metodo destruir, para borrar una orden, pasandole un parametro.
  # DELETE /ordens/1
  # DELETE /ordens/1.xml
  def destroy
    @orden = Orden.find(params[:id])
    @orden.destroy

    respond_to do |format|
      format.html { redirect_to(ordens_url) }
      format.xml  { head :ok }
    end
  end

  def notificar
    @notificacion = Orden.notificaciones
  end

  def nuevanotificacion
    @id = params[:id]
    @orden = Orden.find(@id)
    @orden.notificacion = 'aceptada'
    @orden.save
    redirect_to noti_path
  end

end

courier/app/helpers/ordens_helper.rb
module OrdensHelper
  # Metodo para validar que el ID de la orden concuerde con el usuario.
  def validarOrden (id)
    @historico = Historico.where(:ordens_id => id , :tipo => 'inicio').first
    if @historico.nil?
      @historico = link_to t('enviar'), enviar_path(id)
    else
      @historico = 'Enviado'
    end
  end
  # Metodo para validar botones para administrado dependiendo del usuario que quiera ver
  def retorno(id)
    @persona = Persona.find(id)
    if @persona.empleados_id.nil?
      link_to t('regresar'), ordens_path
    else
      link_to t('regresar'), despachador_path
    end
  end

end

courier/app/views/ordens/_form.html.erb
<%= form_for(@orden) do |f| %>
  <% if @orden.errors.any? %>
    <!-- <div id="error_explanation">
      <h2><%= pluralize(@orden.errors.count, "error") %> prohibited this orden from being saved:</h2>

      <ul>
      <% @orden.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div> -->
  <% end %>
  <div class="field">
    <%= f.label :Nombre_del_Receptor %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :Apellido_del_Receptor %><br />
    <%= f.text_field :apellido %>
  </div>
  <!--<div class="field">
    <%= f.label :Estado %><br />
    <%= f.text_field :estado %>
  </div>
   <div class="field">
    <%= f.label :Fecha %><br />
    <%= f.date_select :fecha %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

courier/app/views/ordens/edit.html.erb
<h1><%= t('editarorden')%></h1>

<%= render 'form' %>

<%= link_to t('mostrar'), @orden %> |
<%= link_to t('regresar'), ordens_path %>

courier/app/views/ordens/index.html.erb
<h1><%= t('listaordenes') %></h1>
<table width="90%">
	<tr>
		<th><%= t('numorden')%></th>
		<th><%= t('receptor')%></th>
		<th><%= t('estado')%></th>
		<th><%= t('fecha')%></th>
		<th></th>
	</tr>
	<% @ordens.each do |orden| %>
	<tr align="center">
		<td><%= orden.id %></td>
		<td><%= orden.nombre + ' ' + orden.apellido %></td>
		<td><%= orden.estado %></td>
		<td><%= orden.fecha %></td>
		<td><%= link_to t('mostrar'), orden %></td>
	</tr>
	<% end %>
</table>
<br />

<%= link_to t('nuevaorden'), paquetes_path %>

courier/app/views/ordens/new.html.erb
<h1>New orden</h1>

<div id='formulario'>
<%= render 'form' %>
</div>
<%= link_to 'Back', ordens_path %>

courier/app/views/ordens/notificar.html.erb
<h1><%= t('listaordenes') %></h1>
<table width="90%">
	<tr>
		<th><%= t('numorden')%></th>
		<th><%= t('estado')%></th>
		<th><%= t('fecha')%></th>
		<th>Nuevo costo</th>
		<th></th>
	</tr>
	<% @notificacion.each do |orden| %>
	<tr align="center">
		<td><%= orden.id %></td>
		<td><%= orden.estado %></td>
		<td><%= orden.fecha %></td>
		<td><%= orden.costoTotal %></td>
		<td><%= link_to 'Aceptar', notis_path(orden.id) %></td>
	</tr>
	<% end %>
</table>
<br />

<%= link_to t('nuevaorden'), paquetes_path %>

courier/app/views/ordens/show.html.erb
<div id="form_container">

	<h1>
	<a></a>
	</h1>
	<form id="form_178611" class="appnitro"  method="post" action="">
		<div class="form_description">
			<h2><%= t("principal.orden") %></h2>
			<p id="notice">
				<%= notice %>
			</p>
		</div>
		<ul >

			<li id="li_1" >
				<span>
					<%= t('receptor') %>: <%= " " + @orden.nombre + ' ' + @orden.apellido %> </br>
					<%= t('fecha') %>: <%= " " + @orden.fecha.to_s %>
					<br/>
					<%= t('estado') %>: <%= " " + @orden.estado %>
				</span>
			</li>
			<li id="li_1" >
				</p>
				<div id='paquetes'>
					<label class="description" for="element_3">
						<%= t('paquetesorden')%>
					</label>

					<table width="90%">
						<tr>
							<th><%= t('nombrez')%></th>
							<th><%= t('peso')%></th>
							<th><%= t('descripcion')%></th>
						</tr>
						<% @paquetes.each do |paquete| %>
						<tr align="center">
							<td><%= paquete.nombre %></td>
							<td><%= paquete.peso %></td>
							<td><%= paquete.descripcion %></td>
						</tr>
						<% end %>
					</table>
				</div>

			</li></br>
			<li id="li_3" >
				<label class="description" for="element_3">
					<%= t("principal.detallado") %>
				</label>
			</li>
			<li id="li_1" >
				<span>	<% @historico.each do |historico| %>
					<%= historico.tipo + " - " + historico.fecha.to_s + ".  " + historico.ciudad + ", " + historico.cPostal  %></br>
					<% end %>
			</li>
		</ul>
		<%= retorno(@orden.personas_id)  %>
	</form>
</div>