courier/config/routes.rb
Courier::Application.routes.draw do

  scope "(:locale)", :locale => /es|en-US|en/ do
    resources :direccions

    resources :paquetes

    resources :compania

    resources :facturas

    resources :tipo_pagos

    resources :historicos

    resources :ordens

    resources :personas

    resources :empleados

    resources :enviar

    resources :despachar

    resources :recolectar

    resources :admin

    resources :service

  end

  get "courier/index"

  match '/:locale/contenido', :to => 'courier#contenido', :as => "cont"

  match '/:locale/seguimiento/', :to => 'courier#seguimiento', :as => "seg"

  match '/:locale/empleado/', :to => 'admin#empleados', :as => "emple"

  match '/:locale/admin/', :to => 'admin#index', :as => "adm"

  match 'paquetes/new/:id', :to => 'paquetes#new', :via => 'get', :as => "newpa"

  match '/:locale/despachar', :to => 'despachar#index', :as => "despachador"

  match ':locale/ruta/:id', :to => 'despachar#ver', :as => "ver"

  match ':locale/recolectores/', :to => 'despachar#recolectores', :as => "recolec"

  match ':locale/simulacion/', :to => 'despachar#simulacion', :as => "simul"

  match ':locale/guardarOrden/:id', :to => 'despachar#guardarOrden' , :as => "guardarOrden"

  match ':locale/recoleccionExterna', :to => 'despachar#recoleccionExterna' , :as => "recoExter"

  match ':locale/consultaExterna/:id', :to => 'despachar#consultaExterna' , :as => "consulExter"

  match ':locale/notificar', :to => 'ordens#notificar' , :as => "noti"
  
   match ':locale/nuevanotificacion/:id', :to => 'ordens#nuevanotificacion' , :as => "notis"

  match ':locale/recolectar/', :to => 'recolectar#index', :as => "reco"

  match ':locale/orden/:id', :to => 'recolectar#orden', :as => "recorden"

  match 'tracking/:id', :to => 'enviar#gen_xml', :via => 'get', :as => "genxml"

match ':locale/prueba/', :to => 'service#prueba', :as => "prueba"
  match 'getorden/:id', :to => 'service#getorden', :as => "getorden", :via => 'get'
  match 'setorden', :to => 'service#setorden', :as => "setorden", :via => 'post'

  root :to => "courier#index"

  get 'contenido' => 'courier#contenido'

  match ':controller(/:action(/:id(.:format)))'

end

courier/app/models/historico.rb
class Historico < ActiveRecord::Base

  # Validamos los formularios de la pagina historico, y relacionamos la tabla.
  validates :tipo	 , :presence => true
  belongs_to :ordens
  belongs_to :direccions
  
  # Metodo que devuelve el seguimiento del paquete que se encuentra en la tabla
  # Historico buscando toda la informacion en la tabla.
  def self.seguimiento1(busqueda)
    return Historico.find_by_sql('Select h.fecha, h.tipo , d.ciudad, d.cPostal from historicos h, direccions d where h.direccions_id=d.id and h.fecha is not null and h.ordens_id=' + busqueda.to_s + ' order by h.fecha DESC')
  end

end

courier/app/controllers/historicos_controller.rb
class HistoricosController < ApplicationController
  # GET /historicos
  # GET /historicos.xml
  # Metodo muesta el index de historico
  def index
    @historico = Historico.all

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @historico }
    end
  end

  # GET /historicos/1
  # GET /historicos/1.xml
  # Metodo que muestra un historico
  def show
    @historico = Historico.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @historico }
    end
  end

  # GET /historicos/new
  # GET /historicos/new.xml
  # Metodo para crear un historico
  def new
    @historico = Historico.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @historico }
    end
  end

  # GET /historicos/1/edit
  # Metodo para editar un historico
  def edit
    @historico = Historico.find(params[:id])
  end

  # POST /historicos
  # POST /historicos.xml
  # Metodo para crear un historico
  def create
    @historico = Historico.new(params[:historico])

    respond_to do |format|
      if @historico.save
        NUESTRO_LOG.info "Se guardo el historico correctamente"
        format.html { redirect_to(@historico, :notice => t('historicocreado')) }
        format.xml  { render :xml => @historico, :status => :created, :location => @historico }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @historico.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /historicos/1
  # PUT /historicos/1.xml
  # Metodo para actualizar un historico
  def update
    @historico = Historico.find(params[:id])

    respond_to do |format|
      if @historico.update_attributes(params[:historico])
        format.html { redirect_to(@historico, :notice => t('historicoactualizado')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @historico.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /historicos/1
  # DELETE /historicos/1.xml
  # Metodo para eliminar un historico
  def destroy
    @historico = Historico.find(params[:id])
    @historico.destroy

    respond_to do |format|
      format.html { redirect_to(historicos_url) }
      format.xml  { head :ok }
    end
  end
end

courier/app/helpers/historicos_helper.rb
module HistoricosHelper
end

courier/app/views/historicos/_form.html.erb
<%= form_for(@historico) do |f| %>
  <% if @historico.errors.any? %>
    <!-- <div id="error_explanation">
      <h2><%= pluralize(@historico.errors.count, "error") %> prohibited this historico from being saved:</h2>

      <ul>
      <% @historico.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div> -->
  <% end %>

  <div class="field">
    <%= f.label :Tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :Fecha %><br />
    <%= f.datetime_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

courier/app/views/historicos/edit.html.erb
<h1>Editing historico</h1>

<%= render 'form' %>

<%= link_to 'Show', @historico %> |
<%= link_to 'Back', historicos_path %>

courier/app/views/historicos/index.html.erb
<h1>Listing historicos</h1>

<table>
  <tr>
    <th>Tipo</th>
    <th>Fecha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @historicos.each do |historico| %>
  <tr>
    <td><%= historico.tipo %></td>
    <td><%= historico.fecha %></td>
    <td><%= link_to 'Show', historico %></td>
    <td><%= link_to 'Edit', edit_historico_path(historico) %></td>
    <td><%= link_to 'Destroy', historico, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Historico', new_historico_path %>

courier/app/views/historicos/new.html.erb
<h1>New historico</h1>

<%= render 'form' %>

<%= link_to 'Back', historicos_path %>

courier/app/views/historicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tipo:</b>
  <%= @historico.tipo %>
</p>

<p>
  <b>Fecha:</b>
  <%= @historico.fecha %>
</p>


<%= link_to 'Edit', edit_historico_path(@historico) %> |
<%= link_to 'Back', historicos_path %>